// Evolução das regiões corporais com dor: inicial, 1 mês e 2 meses
(function(){
  let chart=null;
  let itensAtuais=[];
  function regioes(v){ if(typeof regions==='function')return regions(v); const s=String(v??'').trim(); return s?s.split(/[,;|\/]+/).map(x=>x.trim()).filter(Boolean):[]; }
  function normalizar(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();}
  function nota(v){const m=String(v??'').replace(',','.').match(/-?\d+(?:\.\d+)?/);if(!m)return 0;const n=Number(m[0]);return Number.isFinite(n)?n:0;}
  function risco(n,dor=true){if(n>=7)return '🔴';if(n>=4)return '🟠';if(dor)return '🟡';return '🟢';}
  function dados(){
    const iniciais=Array.isArray(DATA.records)?DATA.records:[],r1=Array.isArray(DATA.reavaliacao1MesRows)?DATA.reavaliacao1MesRows:[],r2=Array.isArray(DATA.reavaliacao2MesRows)?DATA.reavaliacao2MesRows:[];
    const m1=new Map(r1.map(r=>[String(r.ID??'').trim(),r])),m2=new Map(r2.map(r=>[String(r.ID??'').trim(),r]));
    const pares=[]; iniciais.forEach(i=>{const id=String(i.id??'').trim(),a=m1.get(id),b=m2.get(id);if(!a&&!b)return;pares.push({id,nome:i.nome,inicial:regioes(i.regiao),mes1:a?regioes(a['Região da dor']):[],mes2:b?regioes(b['Região da dor']):[],notaInicial:Number(i.nota_dor_num)||0,notaMes1:a?nota(a['Nota da dor']):0,notaMes2:b?nota(b['Nota da dor']):0});});
    return{total:iniciais.length,reavaliados1:r1.filter(r=>String(r.ID??'').trim()).length,reavaliados2:r2.filter(r=>String(r.ID??'').trim()).length,pares};
  }
  function montarItens(d){
    const canon=new Map(); const garantir=label=>{const key=normalizar(label);if(!key)return null;if(!canon.has(key))canon.set(key,{key,label,inicial:[],mes1:[],mes2:[]});return canon.get(key);};
    d.pares.forEach(p=>{['inicial','mes1','mes2'].forEach(campo=>{[...new Set(p[campo].map(x=>normalizar(x)))].forEach(key=>{const label=p[campo].find(x=>normalizar(x)===key)||key,item=garantir(label);if(item)item[campo].push({id:p.id,nome:p.nome,nota:campo==='inicial'?p.notaInicial:campo==='mes1'?p.notaMes1:p.notaMes2});});});});
    return[...canon.values()].sort((a,b)=>Math.max(b.inicial.length,b.mes1.length,b.mes2.length)-Math.max(a.inicial.length,a.mes1.length,a.mes2.length)||String(a.label).localeCompare(String(b.label),'pt-BR'));
  }
  function bloco(){
    let el=document.getElementById('evolucaoRegioesSection');if(el)return el;const setorCanvas=document.getElementById('setorChart'),setorSection=setorCanvas?setorCanvas.closest('.dashboard-chart-section,.section'):null,grid=setorSection?setorSection.parentElement:null,executivo=grid?grid.querySelector('.dashboard-evolution-section'):null;if(!grid||!setorSection)return null;const antigo=document.getElementById('regChart');if(antigo)antigo.style.display='none';
    el=document.createElement('div');el.id='evolucaoRegioesSection';el.className='section dashboard-chart-section';el.innerHTML=`<div class="ev-reg-head"><div><h3><span class="section-dot">◈</span>Dor por região corporal</h3><div class="ev-reg-sub">Avaliação inicial × 1 mês × 2 meses.</div></div></div><div class="ev-reg-chartbox"><canvas id="evRegChart"></canvas></div><div id="evRegNota" class="ev-reg-nota"></div>`;if(executivo)grid.insertBefore(el,executivo);else setorSection.insertAdjacentElement('afterend',el);setorSection.style.gridColumn='auto';el.style.gridColumn='auto';
    if(!document.getElementById('evRegStyles')){const s=document.createElement('style');s.id='evRegStyles';s.textContent=`#evolucaoRegioesSection{margin-top:0}.ev-reg-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap;margin-bottom:10px}.ev-reg-head h3{margin:0}.ev-reg-sub{font-size:12px;color:#667085;margin-top:4px}.ev-reg-chartbox{height:320px;position:relative}.ev-reg-nota{font-size:11px;color:#667085;margin-top:8px;line-height:1.45}.region-click-list{display:flex;flex-direction:column;gap:5px;margin-top:10px}.region-click-person{display:flex;align-items:center;gap:8px;border:1px solid rgba(6,64,1,.12);border-radius:8px;padding:7px 9px;background:#fff;cursor:pointer;min-height:35px}.region-click-person:hover{background:#f7fbf5}.region-click-person .risk-dot{flex:0 0 auto}.region-click-person .region-click-name{font-weight:600;color:#1f2937;min-width:0;font-size:12px;line-height:1.2}@media(max-width:760px){.ev-reg-chartbox{height:360px}}`;document.head.appendChild(s);}return el;
  }
  function abrirDetalheRegiao(index,datasetIndex){
    const item=itensAtuais[index];if(!item)return;const campo=datasetIndex===2?'mes2':datasetIndex===1?'mes1':'inicial',pessoas=item[campo].slice().sort((a,b)=>b.nota-a.nota||String(a.nome).localeCompare(String(b.nome),'pt-BR'));const estilo=campo==='mes2'?'color:#2563eb;background:#eff6ff;border-color:#bfdbfe':campo==='mes1'?'color:#187900;background:#edf8ea;border-color:rgba(24,121,0,.18)':'color:#fd3105;background:rgba(253,49,5,.06);border-color:rgba(253,49,5,.18)',rotulo=campo==='mes2'?'2 meses':campo==='mes1'?'1 mês':'Inicial';const badge=`<span style="font-size:10px;font-weight:700;${estilo};border:1px solid;padding:4px 7px;border-radius:999px;margin-left:5px">${rotulo}</span>`;const lista=pessoas.map(p=>{const id=Number(p.id),acao=Number.isFinite(id)?` onclick="openPersonById(${id})"`:'';return`<div class="region-click-person"${acao}><span class="risk-dot">${risco(p.nota,true)}</span><span class="region-click-name">${esc(p.nome)}</span></div>`;}).join('');const painel=document.getElementById('detailPanel');painel.classList.add('region-detail-panel');painel.removeAttribute('style');document.getElementById('detailContent').innerHTML=`<h2 style="font-size:17px;margin:2px 0 10px">Região: ${esc(item.label)} ${badge}</h2><div class="note" style="font-size:11px;margin-top:0">${pessoas.length} colaborador(es) com queixa nessa região.</div><div class="region-click-list">${lista||'<div class="small">Sem colaboradores nesta região.</div>'}</div>`;painel.style.display='block';
  }
  window.renderEvolucaoRegioes1Mes=function(){
    if(!bloco())return;const d=dados();itensAtuais=montarItens(d);document.getElementById('evRegNota').textContent=d.reavaliados2?`Comparativo: ${d.reavaliados1} reavaliados no 1º mês e ${d.reavaliados2} no 2º mês. Clique em uma barra para ver os nomes.`:`Comparativo com ${d.reavaliados1} reavaliados no 1º mês. O 2º mês aparecerá conforme os registros forem preenchidos.`;if(chart)chart.destroy();
    const datasets=[{label:'Avaliação inicial',data:itensAtuais.map(x=>x.inicial.length),backgroundColor:'rgba(253,49,5,.28)',borderColor:'#fd3105',borderWidth:1,borderRadius:5},{label:'1 mês',data:itensAtuais.map(x=>x.mes1.length),backgroundColor:'rgba(23,250,3,.25)',borderColor:'#187900',borderWidth:1,borderRadius:5}];if(d.reavaliados2)datasets.push({label:'2 meses',data:itensAtuais.map(x=>x.mes2.length),backgroundColor:'rgba(37,99,235,.20)',borderColor:'#2563eb',borderWidth:1,borderRadius:5});chart=new Chart(document.getElementById('evRegChart'),{type:'bar',data:{labels:itensAtuais.map(x=>x.label),datasets},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,onClick:(evt,elements)=>{if(elements.length)abrirDetalheRegiao(elements[0].index,elements[0].datasetIndex);},plugins:{legend:{position:'top'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${c.raw} colaborador(es)`,afterLabel:()=> 'Clique para ver os nomes'}}},scales:{x:{beginAtZero:true,ticks:{precision:0}},y:{grid:{display:false}}}}});
  };
})();